### PR TITLE
CSS Fixes and a few spacing adjustments

### PR DESCRIPTION
**Pull request by joshuarule**
Mostly cleaning up some legacy flex-box code and then fixing some firefox bugs. I tweaked a bit of spacing here and there.

### CODE REVIEW

**Comment by thibaultzanini** [comment]
@joshuarule LGTM, Can I merge it ?

**Comment by joshuarule** [comment]
yeah my changes should be good to go.

**Comment by thibaultzanini** [comment]
cool

**Comment by thibaultzanini** [comment]
@joshuarule @marchant  IOS 6-6.1 supports just the old flexbox specification. 
Do we still support IOS 6?

**Pull request merged**
